# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='menu',
        ),
    ]
