# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_remove_permissions_memu'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='gmid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xxx', to='rbac.Permissions', verbose_name='组内菜单'),
        ),
    ]
