# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20180606_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(default='默认组', max_length=32, verbose_name='表名称'),
        ),
    ]
