# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-05 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20180428_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '中')], default=1, verbose_name='性别'),
        ),
    ]
