# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20180505_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='当前登录用户的session_key'),
        ),
    ]
