# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20180522_1613'),
        ('rbac', '0009_auto_20180606_1557'),
    ]

    operations = [
    ]
