# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20180606_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='title',
            field=models.CharField(max_length=32, verbose_name='权限名称'),
        ),
    ]
