# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20180613_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='Model_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='model注册名'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='一级菜单'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(default='默认', max_length=32, verbose_name='表名称'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.PermissionGroup', verbose_name='表'),
        ),
    ]
