# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20180515_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='一级菜单'),
        ),
    ]
