# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20180614_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='Model_name',
            new_name='model_name',
        ),
    ]
