# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20180614_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='name',
            field=models.CharField(default='默认', max_length=32, verbose_name='db_table'),
        ),
    ]
