# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_auto_20180614_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ldap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='name')),
            ],
        ),
    ]
