# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.CharField(max_length=32, verbose_name='所属权限组'),
        ),
    ]
