# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180110_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='groupid',
            field=models.SmallIntegerField(default=1, verbose_name='所属权限组id'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.PermissionGroup', verbose_name='所属权限组'),
        ),
    ]
