# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20180112_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='所属菜单'),
        ),
    ]
