# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20180112_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='menu',
        ),
    ]
