# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_remove_permissiongroup_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='group_menu',
        ),
    ]
