# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20180112_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='caption',
            field=models.CharField(max_length=32),
        ),
    ]
