<style type="text/css">
.t_serverbox{ background:#f4f4f4; }
.t_server{width:1000px; margin:0 auto; padding:50px 0 35px;}
.t_server ul{position:relative; overflow:hidden; padding-bottom:5px;}
.t_server li{ float:left; display:inline; width:199px;padding-bottom:4000px; margin-bottom:-4000px;}
.t_server dl{ padding-left:45px; font-size:13px; line-height:1.8em;}
.t_server dt{ padding-bottom:15px; font-size:14px;}
.t_server a{ color:#999;}
.t_server a:hover{ text-decoration:none; color:#08c;}
</style>
<div class="t_serverbox">
<div class="t_server">
	<ul class="clearfix">
    	<li>
        	<dl>
            	<dt>购物指南</dt>
                <dd><a href="http://feature.mtime.com/mall/help/page-1.html" target="_blank">新用户注册</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-2.html" target="_blank">购物流程</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-3.html" target="_blank">常见问题</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-4.html" target="_blank">发票制度</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-5.html" target="_blank">联系我们</a></dd>
            </dl>
        </li>
        <li>
        	<dl>
            	<dt>支付方式</dt>
                <dd><a href="http://feature.mtime.com/mall/help/page-6.html" target="_blank">在线付款</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-7.html" target="_blank">余额付款</a></dd>
				<dd><a href="http://feature.mtime.com/mall/help/page-16.html" target="_blank">礼品卡付款</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-8.html" target="_blank">优惠券使用说明</a></dd>
            </dl>
        </li>
        <li>
        	<dl>
            	<dt>配送方式</dt>
                <dd><a href="http://feature.mtime.com/mall/help/page-9.html" target="_blank">邮费说明</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-10.html" target="_blank">配送服务范围</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-11.html" target="_blank">配送速度查询</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-12.html" target="_blank">验货与签收</a></dd>
            </dl>
        </li>
        <li>
        	<dl>
            	<dt>售后服务</dt>
                <dd><a href="http://feature.mtime.com/mall/help/page-13.html" target="_blank">售后政策</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-14.html" target="_blank">退货政策</a></dd>
                <dd><a href="http://feature.mtime.com/mall/help/page-15.html" target="_blank">退货流程</a></dd>
            </dl>
        </li>
        <li>
        	<dl>
            	<dt>客服电话</dt>
                <dd class="px22">4006-118-118</dd>
                <dd class="c_94 mt5">周一至周日9:00-22:00</dd>
            </dl>
        </li>
    </ul>
</div>
</div>