<link type="image/x-icon" href="http://static1.mtime.cn/favicon.ico" rel="icon">
<link type="image/x-icon" href="http://static1.mtime.cn/favicon.ico" rel="shortcut icon">
<link type="image/x-icon" href="http://static1.mtime.cn/favicon.ico" rel="bookmark">
<link href="http://static1.mtime.cn/static/css/2014/publicpack.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="css/main.css?2017042621003">
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta content="telephone=no" name="format-detection" />
<meta name="viewport" content="width=device-width,maximum-scale=1,user-scalable=no">