# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171118_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
