# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=32),
        ),
    ]
