# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20180320_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='port',
        ),
        migrations.AddField(
            model_name='host',
            name='remoteip',
            field=models.GenericIPAddressField(default='0.0.0.0.', protocol='ipv4'),
        ),
        migrations.AddField(
            model_name='host',
            name='sn',
            field=models.CharField(default='000', max_length=32),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=32, verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
