# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20180321_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.CharField(default='廊坊', max_length=32),
        ),
    ]
