# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机柜名')),
                ('postion', models.CharField(max_length=32, verbose_name='机柜位')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=32, verbose_name='sn号')),
                ('remoteip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='带外ip')),
                ('hostname', models.CharField(default='', max_length=32, verbose_name='主机名')),
                ('host_ip', models.CharField(default='0.0.0.0', max_length=32, verbose_name='主机ip')),
                ('manufacturer', models.CharField(default='', max_length=32, verbose_name='品牌')),
                ('product_name', models.CharField(default='', max_length=32, verbose_name='型号')),
                ('Hosys', models.CharField(max_length=32, null=True, verbose_name='操作系统')),
                ('Hcore', models.CharField(max_length=32, null=True, verbose_name='内核架构')),
                ('Hcpu', models.CharField(default='', max_length=64, verbose_name='cpu')),
                ('Hmemory', models.CharField(default='', max_length=32, verbose_name='内存')),
                ('Hdisk', models.CharField(default='', max_length=64, verbose_name='磁盘')),
                ('HotherIp', models.CharField(default='', max_length=128, verbose_name='其它ip')),
                ('Hother', models.CharField(default='', max_length=128, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iname', models.CharField(max_length=32, unique=True, verbose_name='机房名称')),
                ('Icity', models.CharField(max_length=32, verbose_name='城市')),
                ('Iaddr', models.CharField(max_length=32, verbose_name='地址')),
                ('Itel', models.CharField(max_length=32, verbose_name='电话')),
                ('Icontact', models.CharField(max_length=32, verbose_name='联系人')),
            ],
        ),
        migrations.CreateModel(
            name='TBServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tname', models.CharField(blank=True, max_length=32, null=True, verbose_name='名称')),
                ('Tip', models.CharField(blank=True, max_length=32, null=True, verbose_name='ip')),
                ('Tuser', models.CharField(blank=True, max_length=32, null=True, verbose_name='跳扳机用户')),
                ('Tpassword', models.CharField(blank=True, max_length=64, null=True, verbose_name='跳扳机密码')),
                ('Tidc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='Vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Host', verbose_name='宿主机')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='Zabbix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zname', models.CharField(max_length=32, verbose_name='name')),
                ('Zip', models.CharField(default='0.0.0.0', max_length=32, verbose_name='zabbix_ip')),
                ('Zapi', models.CharField(blank=True, max_length=128, null=True, verbose_name='API_url')),
                ('Zadmin', models.CharField(default='Admin', max_length=16, verbose_name='zabbix-admin')),
                ('ZabbixPassword', models.CharField(blank=True, max_length=32, null=True, verbose_name='zabbix-密码')),
                ('Zstatus', models.IntegerField(choices=[(1, '错误'), (2, 'OK')], default=1, verbose_name='状态')),
                ('Ztoken', models.CharField(blank=True, max_length=64, null=True, verbose_name='token')),
                ('Zidc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房')),
            ],
        ),
        migrations.CreateModel(
            name='ZabbixTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.IntegerField(blank=True, null=True, verbose_name='模板id')),
                ('Tname', models.CharField(max_length=32, verbose_name='name')),
                ('Tzabbix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Zabbix', verbose_name='zabbix')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房'),
        ),
    ]
