# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='VCPUs',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vdisk',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='磁盘'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vmac',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MAC'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vmem',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VMname'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vnetworks',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vos',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OS'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='Vstatus',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='uuid'),
        ),
    ]
