# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='Hcpu',
        ),
        migrations.RemoveField(
            model_name='host',
            name='Hdisk',
        ),
        migrations.RemoveField(
            model_name='host',
            name='Hmemory',
        ),
        migrations.RemoveField(
            model_name='host',
            name='Hosys',
        ),
        migrations.RemoveField(
            model_name='host',
            name='HotherIp',
        ),
    ]
