# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180606_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Hcpu',
            field=models.CharField(default='', max_length=32, verbose_name='cpu'),
        ),
        migrations.AddField(
            model_name='host',
            name='Hdisk',
            field=models.CharField(default='', max_length=32, verbose_name='磁盘'),
        ),
        migrations.AddField(
            model_name='host',
            name='Hmemory',
            field=models.CharField(default='', max_length=32, verbose_name='内存'),
        ),
        migrations.AddField(
            model_name='host',
            name='Hosys',
            field=models.CharField(max_length=32, null=True, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='host',
            name='HotherIp',
            field=models.CharField(default='', max_length=128, verbose_name='其它ip'),
        ),
    ]
