# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180727_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vhost',
            name='idc',
        ),
    ]
