# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180606_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Hcore',
            field=models.CharField(max_length=32, null=True, verbose_name='内核架构'),
        ),
    ]
