# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_host_hcore'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Hother',
            field=models.CharField(default='', max_length=128, verbose_name='备注'),
        ),
    ]
