# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_zabbix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Host', verbose_name='宿主机')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房')),
            ],
        ),
    ]
