# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_vhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zname', models.CharField(max_length=32, verbose_name='name')),
                ('Zip', models.CharField(default='0.0.0.0', max_length=32, verbose_name='zabbix_ip')),
                ('Zidc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.IDC', verbose_name='机房')),
            ],
        ),
    ]
