# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180330_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='角色名称'),
        ),
    ]
