# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20180402_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='title',
            field=models.CharField(max_length=32, unique=True, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
