# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_auto_20180406_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='父菜单'),
        ),
    ]
