# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20180406_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permisions',
            new_name='permissions',
        ),
    ]
