# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_userinfo_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='closed_name',
            field=models.CharField(max_length=32, null=True, verbose_name='爱人'),
        ),
    ]
