# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('gp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
