# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userinfo_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='love',
        ),
    ]
