# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('pubDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('publish', models.CharField(max_length=32)),
            ],
        ),
    ]
